name: docgen-update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Determine diff base
        id: diff
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "base=${{ github.event.pull_request.base.sha }}" >> "$GITHUB_OUTPUT"
          else
            echo "base=origin/main" >> "$GITHUB_OUTPUT"
          fi

      - name: Run docgen update
        env:
          DOCGEN_LLM_BASE_URL: http://localhost:12434/engines/v1
        run: python -m docgen.cli update --diff-base ${{ steps.diff.outputs.base }}

      - name: Commit README.md (optional)
        run: |
          if git status --short | grep -q README.md; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git commit -am "docs: update README via docgen"
          fi
